<a href="https://colab.research.google.com/github/marianwitkowski/python-data/blob/master/wielomiany-rownania.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

## Tworzenie wielomianu

In [2]:
# 2x^2 -4x + 5
wielomian = np.poly1d([2, -4, 5])
print(wielomian)

   2
2 x - 4 x + 5


In [4]:
# wynik wielomianu dla argumentu x = 5
print( wielomian(5) )

35


In [5]:
# miejsca zerowe wielomianu to -3 i 2 -> znajdź wielomian
wielomian = np.poly1d([-3, 2], r=True)
print(wielomian)

   2
1 x + 1 x - 6


In [7]:
# sprawdzenie
wielomian(-3), wielomian(2)

(0.0, 0.0)

In [9]:
wielomian.r #miejsca zerowe

array([-3.,  2.])

In [11]:
wielomian.c #wspołczynniki

array([ 1.,  1., -6.])

In [12]:
wielomian.o #rząd wielomianu

2

In [13]:
print(wielomian.deriv()) # 1-wa pochodna

 
2 x + 1


In [14]:
print(wielomian.deriv(2)) # 2-ga pochodna

 
2


## Działania na wielomianach

In [15]:
wielomian1 = np.poly1d([3,2,-1])
print(wielomian1)
wielomian2 = np.poly1d([-4,5])
print(wielomian2)

   2
3 x + 2 x - 1
 
-4 x + 5


In [16]:
print(wielomian1 + wielomian2)

   2
3 x - 2 x + 4


In [17]:
print(wielomian1 - wielomian2)

   2
3 x + 6 x - 6


In [18]:
print(wielomian1 * wielomian2)

     3     2
-12 x + 7 x + 14 x - 5


In [19]:
wielomian, reszta = wielomian1/wielomian2
print(wielomian, reszta)

 
-0.75 x - 1.438  
6.188


## Rozwiązywanie układu 3 równań z 3 niewiadomymi

In [28]:
A = np.array([[4, 3, 2], [-2, 2, 3], [3, -5, 2]])
A

array([[ 4,  3,  2],
       [-2,  2,  3],
       [ 3, -5,  2]])

In [29]:
B = np.array([25, -10, -4])
B

array([ 25, -10,  -4])

In [30]:
X = np.linalg.solve(A,B)
X

array([ 5.,  3., -2.])